### ISSUE TITLE
build.xml copy-generated-source-to-opendis7-java target adds to scr-generated folder files that are not generated by JavaGenerator

### ISSUE THREAD

**Issue by mimmi-matalamaki-insta-fi** [open-dis/opendis7-source-generator#7]
target name="copy-generated-source-to-opendis7-java" copies files to dir="${opendis7-java}/src-generated" that are not generated by JavaGenerator.java and are not found on opendis7-source-generator project src-generated folder. (opendis7-source-generator projects' src-generated folder contains only files generated by JavaGenerator.java.) 
-> Confusing moments for developers. 

Solutions idea: a new ant target to opendis7-source-generator projects' build.xml for copying files from src-specialcase folder to folder that has the same name in opendis7-java project.

**Comment by brutzman** [comment]
Thanks for comment.  In general, sources that exist in the _src-specialcase_ directory are those that otherwise are not correctly autogenerated.  Over time, hopefully, this set of files will get produced correctly and then special cases will no longer be necessary.

- https://github.com/open-dis/opendis7-source-generator/tree/master/src-specialcase
